<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.0.0-beta2</Version>
    <ApplicationIcon>Resources\Icon\ICON_256.ico</ApplicationIcon>
	<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
	<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\app_names.json" />
    <None Remove="Resources\Fonts\CascadiaCode\CascadiaCode.ttf" />
    <None Remove="Resources\Fonts\CascadiaMono\CascadiaMono.ttf" />
    <None Remove="Resources\Fonts\Consolas\consola.ttf" />
    <None Remove="Resources\Fonts\Consolas\consolab.ttf" />
    <None Remove="Resources\Fonts\Consolas\consolai.ttf" />
    <None Remove="Resources\Fonts\Consolas\consolaz.ttf" />
    <None Remove="Resources\Fonts\HarmonyOS_Sans_SC\HarmonyOS_Sans_SC_Black.ttf" />
    <None Remove="Resources\Fonts\HarmonyOS_Sans_SC\HarmonyOS_Sans_SC_Bold.ttf" />
    <None Remove="Resources\Fonts\HarmonyOS_Sans_SC\HarmonyOS_Sans_SC_Medium.ttf" />
    <None Remove="Resources\Fonts\Microsoft_YaHei_UI\msyh.ttc" />
    <None Remove="Resources\Fonts\Microsoft_YaHei_UI\msyhbd.ttc" />
    <None Remove="Resources\Fonts\Microsoft_YaHei_UI\msyhl.ttc" />
    <None Remove="Resources\hdc.exe" />
    <None Remove="Resources\libusb_shared.dll" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Icon\ICON_256.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\app_names.json" />
    <EmbeddedResource Include="Resources\Fonts\CascadiaCode\CascadiaCode.ttf" />
    <EmbeddedResource Include="Resources\Fonts\CascadiaMono\CascadiaMono.ttf" />
    <EmbeddedResource Include="Resources\Fonts\Consolas\consola.ttf" />
    <EmbeddedResource Include="Resources\Fonts\Consolas\consolab.ttf" />
    <EmbeddedResource Include="Resources\Fonts\Consolas\consolai.ttf" />
    <EmbeddedResource Include="Resources\Fonts\Consolas\consolaz.ttf" />
    <EmbeddedResource Include="Resources\Fonts\HarmonyOS_Sans_SC\HarmonyOS_Sans_SC_Black.ttf" />
    <EmbeddedResource Include="Resources\Fonts\HarmonyOS_Sans_SC\HarmonyOS_Sans_SC_Bold.ttf" />
    <EmbeddedResource Include="Resources\Fonts\HarmonyOS_Sans_SC\HarmonyOS_Sans_SC_Medium.ttf" />
    <EmbeddedResource Include="Resources\Fonts\Microsoft_YaHei_UI\msyh.ttc" />
    <EmbeddedResource Include="Resources\Fonts\Microsoft_YaHei_UI\msyhbd.ttc" />
    <EmbeddedResource Include="Resources\Fonts\Microsoft_YaHei_UI\msyhl.ttc" />
    <EmbeddedResource Include="Resources\HDC\hdc.exe" />
    <EmbeddedResource Include="Resources\HDC\libusb_shared.dll" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>